import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopMenu from '@/components/TopMenu'
import BottomMenu from '@/components/BottomMenu'
import BottomTag from '@/components/BottomTag'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopMenu/>
        {children}
        <BottomMenu/>
        <BottomTag/>
      </body>
    </html>
  )
}
